# Generated by Django 5.1.1 on 2024-09-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0003_remove_company_created_at_company_ccreated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='ccreated_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('E', 'Employer'), ('J', 'Job Seeker')], max_length=2),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('CON', 'Contract'), ('FR', 'Freelance')], default='FT', max_length=5),
        ),
    ]
